Repository cezaraugusto/You-Dont-Know-JS, pull requests merged in 2018-10, with the labels that each got.

#219 Correções Gramaticais - Capítulo 1
  scope & closures/ch1.md
Labels: Em revisão

#204 Types & Grammar (Tipos e Gramática) - Capítulo 4
  types & grammar/ch4.md
Labels: disponível para revisão

#209 Types & Grammar (Tipos e Gramática) - Capítulo 4 - pt 2
  types & grammar/ch4.md
Labels: disponível para revisão

#211 Tipos e Gramática - Capítulo 2
  types & grammar/ch2.md
Labels: disponível para revisão

#210 Close #12 - Types & Grammar (Tipos e Gramática) - Capítulo 4 - Finalização de CP
  types & grammar/ch4.md
Labels: disponível para revisão

#223 this & Prototipagem de Objetos - cap 4 - introducao
  this & object prototypes/ch4.md
Labels: disponível para revisão

#224 Async & Performance - Foreword
  async & performance/foreword.md
Labels: disponível para revisão

#226 this & Prototipagem de Objetos - cap 4 - Teoria das classes
  this & object prototypes/ch4.md
Labels: Em revisão

#225 Es6 e alem ch2 valores padrao parametro
  es6 & beyond/ch2.md
Labels: disponível para revisão

#229 this & object prototype: correções ortográficas
  this & object prototypes/ch2.md
Labels: Em revisão

#232 Async e Performance - Apêndice A - Sequências, princípio de abstração
  async & performance/apA.md
Labels: Em revisão

#233 Async e Performance - Apêndice A - API, Passos e Erros
  async & performance/apA.md
Labels: disponível para revisão

#235 traducao da parte: Object Property Assignment Pattern
  es6 & beyond/ch2.md
Labels: disponível para revisão

#236 tradução da parte: Not Just Declarations
  es6 & beyond/ch2.md
Labels: disponível para revisão

#237 tradução da parte: Repeated Assignments
  es6 & beyond/ch2.md
Labels: disponível para revisão

#238 es6 e alem ch2 destructuring assignment expressions
  es6 & beyond/ch2.md
Labels: disponível para revisão

#227 tradução da parte: Default Parameter Expressions
  es6 & beyond/ch2.md
Labels: autor/aguardando-resposta
